services:
  wanted:
    build:
      context: .
      args:
        - DEV=true
    working_dir: /app
    environment:
      - DB_HOST=wanted-db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - wanted-db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
  wanted-db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
      
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${DB_USER:-devuser}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  dev-db-data:
  dev-static-data:
